// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyMaster.Infrastructure.Data;

#nullable disable

namespace NotifyMaster.Infrastructure.Migrations
{
    [DbContext(typeof(NotifyMasterDbContext))]
    [Migration("20241210235112_Add_UserReminder_Table")]
    partial class Add_UserReminder_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotifyMaster.Core.Entities.MessageReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan>("Delay")
                        .HasColumnType("time");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationPhase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MessageReminders");
                });

            modelBuilder.Entity("NotifyMaster.Core.Entities.UserReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ReminderMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReminderMessageId");

                    b.ToTable("UserReminders");
                });

            modelBuilder.Entity("NotifyMaster.Core.Entities.UserReminder", b =>
                {
                    b.HasOne("NotifyMaster.Core.Entities.MessageReminder", "ReminderMessage")
                        .WithMany()
                        .HasForeignKey("ReminderMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReminderMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
