services:
  notifymaster.webapi:
    image: notifymasterwebapi
    container_name: notifymaster.webapi
    build:
      context: .
      dockerfile: NotifyMaster.WebApi/Dockerfile
    ports:
       - "8000:5000" 
       - "8001:5000"
    depends_on:       
       - notifymaster.database
  notifymaster.database:    
    image: postgres:latest
    container_name: notifymaster.database    
    restart: always
    environment:         
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root    
    ports:
       - "5432:5432" 
    volumes: 
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql     
       - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4    
    container_name: pgadmin4_container
    restart: always     
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com        
        PGADMIN_DEFAULT_PASSWORD: root
    ports:      
       - "5050:80"
    depends_on:        
       - notifymaster.database
volumes:  
    postgres-data:
